[TEST] ParanoidLauncher: Use a proper UI context for ViewConfiguration.
maybe....

Testing if it fixes:
E StrictMode: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.quickstep.inputconsumers.OtherActivityInputConsumer@13e818e The API:ViewConfiguration needs a proper configuration. Use UI contexts such as an activity or a context created via createWindowContext(Display, int, Bundle) or  createConfigurationContext(Configuration) with a proper configuration.
java.lang.IllegalAccessException: Tried to access the API:ViewConfiguration which needs to have proper configuration from a non-UI Context:com.android.quickstep.inputconsumers.OtherActivityInputConsumer@13e818e
	at android.os.StrictMode.assertConfigurationContext(StrictMode.java:2296)
	at android.view.ViewConfiguration.get(ViewConfiguration.java:522)
	at com.android.quickstep.inputconsumers.OtherActivityInputConsumer.<init>(OtherActivityInputConsumer.java:174)
	at com.android.quickstep.TouchInteractionService.createOtherActivityInputConsumer(TouchInteractionService.java:775)
	at com.android.quickstep.TouchInteractionService.newBaseConsumer(TouchInteractionService.java:759)
	at com.android.quickstep.TouchInteractionService.newConsumer(TouchInteractionService.java:652)
	at com.android.quickstep.TouchInteractionService.onInputEvent(TouchInteractionService.java:549)
	at com.android.quickstep.TouchInteractionService.$r8$lambda$QnySfMPM3HQvC_OREg1W70p37mY(Unknown Source:0)
	at com.android.quickstep.TouchInteractionService$$ExternalSyntheticLambda4.onInputEvent(Unknown Source:2)
	at com.android.systemui.shared.system.InputChannelCompat$InputEventReceiver$1.onInputEvent(InputChannelCompat.java:74)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:260)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7880)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

Signed-off-by: Jyotiraditya Panda <jyotiraditya@aospa.co>
Change-Id: Ifc1ee09060cdd3544a71ff9bf546d0b4d50338ab